# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-HPLOO
version:      0.23
version_from: lib/Class/HPLOO.pm
installdirs:  site
requires:
    Filter::Simple:                0.02
    Filter::Util::Call:            1.06
    Text::Balanced:                1.89

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
